# Generated by Django 3.2.4 on 2022-05-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=26)),
                ('email', models.CharField(blank=True, max_length=26)),
                ('password', models.CharField(blank=True, max_length=220)),
            ],
        ),
    ]
